# site settings
title: Online Ads Expert
subtitle: 
email: hello@onlineadsexpert.com
description: A responsive site template designed by HTML5 Up<br /> and released under the Creative Commons.
baseurl: "" # the subpath of your site, e.g. /blog
url: "http://onlineadsexpert.com" # the base hostname & protocol for your site
author:
street_address:
city: Folsom
state: CA
zip_code: 95630
country: United States of America
phone: (757) 632-5331

# homepage tiles
tiles-source: pages # accepts "posts" or "pages"
tiles-count: 4

# social settings
500px_url:
facebook_url: https://facebook.com/onlineadsexpert
github_url:
gitlab_url:
googleplus_url: 
instagram_url: 
linkedin_url: 
pinterest_url:
slack_url:
twitter_url: https://twitter.com/onlineadsexpert

# build settings
markdown: kramdown

sass:
  style: compressed
